### ISSUE TITLE
Add Polkadot as a Chain

### ISSUE THREAD

**Issue by dillchen** [hicommonwealth/chain-events#16]
Currently getting an unexpected chain for Polkadot Chain Events

**Comment by jnaviask** [comment]
We might need a migration on the db side, or a library update to make this function. Will need to look at the current db.

**Comment by dillchen** [comment]
@zakhap mentioned this error.

I think it's just potentially a trivial fix. In the same way that I added KLP as a chain, DOT should be added.

https://github.com/hicommonwealth/chain-events/blob/8ed28aa0f0173b64d8c9ddbf90b5c344244f8415/src/substrate/filters/labeler.ts#L40-L49
