### ISSUE TITLE
Publish new version 0.2.16 to NPM

### ISSUE THREAD

**Issue by drewstone** [hicommonwealth/chain-events#24]

**Comment by jnaviask** [comment]
The update to @edgeware/node-types broke the compilation of chain-events. I will fix this and then publish.

**Comment by jnaviask** [comment]
Asking Jaco about this, because I can't figure out what's happening here.

**Comment by drewstone** [comment]
Ok I did publish this version already so I’ll edit to be 0.2.16

**Comment by jnaviask** [comment]
How did you publish if the `tsc` build command throws errors?
